# Generated by Django 5.2.1 on 2025-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_images/default.jpg', upload_to='user_images'),
        ),
    ]
