# Generated by Django 5.2.1 on 2025-08-01 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_id_alter_user_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='UserProfile',
        ),
    ]
