# Generated by Django 5.2.1 on 2025-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_detail',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
