# Generated by Django 5.2.1 on 2025-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_detail_assigned_to_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
