# Generated by Django 5.2.1 on 2025-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_assigned_to_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=20),
        ),
    ]
