# Generated by Django 5.2.1 on 2025-07-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_task_image_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_image',
        ),
        migrations.AddField(
            model_name='task_detail',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images'),
        ),
    ]
