# Generated by Django 5.2.1 on 2025-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_project_alter_task_detail_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(related_name='employees', to='tasks.employee'),
        ),
    ]
