# Generated by Django 5.2.1 on 2025-08-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_detail_task_image_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=20),
        ),
    ]
